~VERSION INFORMATION
 VERS.                           2.00:        CWLS LOG ASCII STANDARD - VERSION 2.00
 WRAP.                             NO:        ONE LINE PER DEPTH STEP
~WELL INFORMATION
#MNEM.UNIT                   DATA             INFORMATION
#----------             --------------        ------------------------------
 STRT.F                     7524.0000:        START DEPTH
 STOP.F                     7533.0000:        STOP DEPTH
 STEP.F                        0.5000:        STEP VALUE
 NULL.                      -999.2500:        NULL VALUE
 COMP.                               :        COMPANY
 LOC .                               :        LOCATION
 DATE.                               :        LOG DATE
 WELL.                      DALTON #1:        WELL
 UWI .                               :        UNIQUE WELL ID
 API .                               :        UNIQUE WELL IDENTIFIER
~CURVE INFORMATION      
#MNEM        .UNIT         API CODE           CURVE DESCRIPTION
#-----------------      --------------        ------------------------------
 DEPT        .F                      :        1  DEPTH
 GR          .API                    :        2  
~PARAMETER INFORMATION
#MNEM.UNIT                  VALUE             DESCRIPTION OF MNEMONIC
#---------             ---------------        ------------------------------
 EKB .F                        0.0000:        KELLY BUSHING
 TD  .F                        0.0000:        TOTAL DEPTH
~OTHER INFORMATION
~A    DEPTH          GR 
  7524.0000      9.7717 
  7524.5000     10.7300 
  7525.0000     13.1151 
  7525.5000     12.0685 
  7526.0000     13.2463 
  7526.5000     17.5729 
  7527.0000     14.6389 
  7527.5000     12.3881 
  7528.0000     17.8409 
  7528.5000     16.1156 
  7529.0000     12.7929 
  7529.5000     15.4269 
  7530.0000     12.4046 
  7530.5000     12.9622 
  7531.0000     10.5034 
  7531.5000      8.6922 
  7532.0000      8.4477 
  7532.5000      9.6734 
  7533.0000     10.9504 

